matrix:
    include:
        - os: linux
          sudo: required
          services: docker
          script: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build 
        - os: linux
          language: python
          python: 2.7
          env: TOXENV=py27,py36
          install: pip install tox
          script: tox
